
name: TEMPLATE_PYTHON_PACKAGE Image Builder

# Publish on new pushed, and build on Monday Morning (UTC) regardless.
# on:
#   push:
#     branches:
#       - 'main'
#   schedule:
#     - cron:  '4 0 * * MON'

jobs:
  Uvicorn-Builder:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_versions: ["3.8", "3.9", "3.10"]
        package_versions: []
        target_base: ["full", "slim", "alpine"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Create and push"
        uses: multi-py/action-python-image-builder@main
        with:
          package: "TEMPLATE_PYTHON_PACKAGE"
          package_latest_version: ""
          maintainer: "Robert Hafner <tedivm@tedivm.com>"
          python_version: ${{ matrix.python_versions }}
          target_base: ${{ matrix.target_base }}
          package_version: ${{ matrix.package_versions }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
