
name: TEMPLATE_PYTHON_PACKAGE Image Builder

on:
  push:
    branches:
      - 'CHANGEME'
    paths-ignore:
      - '**/README.md'
      - 'templates/**'
      - ".github/workflows/versionator.yml"
  schedule:
    - cron:  '4 0 * * MON'

jobs:
  Uvicorn-Builder:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_versions: ["3.6", "3.7", "3.8", "3.9", "3.10"] 
        package_versions: ["0.1.0", "0.1.1"]
        target_base: ["full", "slim", "alpine"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Create and push"
        uses: multi-py/action-python-image-builder@main
        with:
          package: "TEMPLATE_PYTHON_PACKAGE"
          package_latest_version: "0.1.1"
          maintainer: "Robert Hafner <tedivm@tedivm.com>"
          python_version: ${{ matrix.python_versions }}
          target_base: ${{ matrix.target_base }}
          package_version: ${{ matrix.package_versions }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

          # Uncomment to use local docker files instead of action ones.
          #dockerfile: "${{ github.workspace }}/dockerfile"
          #docker_build_path: "${{ github.workspace }}/"

